baseURL = 'https://sarah-lecinski.github.io'
publishDir = "docs"
languageCode = 'en-us'
title = 'sarah-lecinski'
enableEmoji = 'true'
theme = "paper"




[params]
  # color style
  color = 'light'                           # linen, wheat, gray, light

	

  # header social icons
  
  github = 'slecinski'                 # github.com/YOUR_GITHUB_ID
  twitter = 'LecinskiSarah'               # twitter.com/YOUR_TWITTER_ID
  #linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID

  # home page profile
  avatar = 'sarah.lecinski@york.ac.uk'                 # gravatar email or image url
  name = 'Welcome to my website'
  bio = 'In here you can find record of my scientific activities.'
  
  
  [menu]

  [[menu.main]]
    identifier = "contact"
    name = "My Socials : "
    #url = "/contact/"
    weight = -10
